language : "pt_core_news_lg"

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 220
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 220

policies:
  - name: TEDPolicy
    epochs: 50
    featurizer:
    - name: MaxHistoryTrackerFeaturizer
      max_history: 5
      state_featurizer:
        - name: BinarySingleStateFeaturizer
  - name: "FormPolicy"
  - name: MemoizationPolicy
    max_history: 5
  - name: MappingPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.5
    core_threshold: 0.5
    fallback_action_name: "utter_base_fallback"
